/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'dashboard': RouteRecordInfo<'dashboard', '/dashboard', Record<never, never>, Record<never, never>>,
    'iqc': RouteRecordInfo<'iqc', '/iqc', Record<never, never>, Record<never, never>>,
    'iqc-incoming-part-report': RouteRecordInfo<'iqc-incoming-part-report', '/iqc/incoming-part-report', Record<never, never>, Record<never, never>>,
    'iqc-incoming-part-report-components-iir-add-edit-dialog': RouteRecordInfo<'iqc-incoming-part-report-components-iir-add-edit-dialog', '/iqc/incoming-part-report/components/IirAddEditDialog', Record<never, never>, Record<never, never>>,
    'iqc-incoming-part-report-components-iir-delete-dialog': RouteRecordInfo<'iqc-incoming-part-report-components-iir-delete-dialog', '/iqc/incoming-part-report/components/IirDeleteDialog', Record<never, never>, Record<never, never>>,
    'iqc-incoming-part-report-components-iir-filter-form': RouteRecordInfo<'iqc-incoming-part-report-components-iir-filter-form', '/iqc/incoming-part-report/components/IirFilterForm', Record<never, never>, Record<never, never>>,
    'iqc-incoming-part-report-components-iir-message-dialog': RouteRecordInfo<'iqc-incoming-part-report-components-iir-message-dialog', '/iqc/incoming-part-report/components/IirMessageDialog', Record<never, never>, Record<never, never>>,
    'iqc-incoming-part-report-components-iir-table': RouteRecordInfo<'iqc-incoming-part-report-components-iir-table', '/iqc/incoming-part-report/components/IirTable', Record<never, never>, Record<never, never>>,
    'iqc-incoming-part-report-index-ipr-backup': RouteRecordInfo<'iqc-incoming-part-report-index-ipr-backup', '/iqc/incoming-part-report/index-ipr/backup', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'materials': RouteRecordInfo<'materials', '/materials', Record<never, never>, Record<never, never>>,
    'materials-components-material-add-edit-dialog': RouteRecordInfo<'materials-components-material-add-edit-dialog', '/materials/components/MaterialAddEditDialog', Record<never, never>, Record<never, never>>,
    'materials-components-material-delete-dialog': RouteRecordInfo<'materials-components-material-delete-dialog', '/materials/components/MaterialDeleteDialog', Record<never, never>, Record<never, never>>,
    'materials-components-material-filter-form': RouteRecordInfo<'materials-components-material-filter-form', '/materials/components/MaterialFilterForm', Record<never, never>, Record<never, never>>,
    'materials-components-material-message-dialog': RouteRecordInfo<'materials-components-material-message-dialog', '/materials/components/MaterialMessageDialog', Record<never, never>, Record<never, never>>,
    'materials-components-material-table': RouteRecordInfo<'materials-components-material-table', '/materials/components/MaterialTable', Record<never, never>, Record<never, never>>,
    'qc-handovers': RouteRecordInfo<'qc-handovers', '/qc-handovers', Record<never, never>, Record<never, never>>,
    'second-page': RouteRecordInfo<'second-page', '/second-page', Record<never, never>, Record<never, never>>,
    'suppliers': RouteRecordInfo<'suppliers', '/suppliers', Record<never, never>, Record<never, never>>,
    'suppliers-components-supplier-add-edit-dialog': RouteRecordInfo<'suppliers-components-supplier-add-edit-dialog', '/suppliers/components/SupplierAddEditDialog', Record<never, never>, Record<never, never>>,
    'suppliers-components-supplier-delete-dialog': RouteRecordInfo<'suppliers-components-supplier-delete-dialog', '/suppliers/components/SupplierDeleteDialog', Record<never, never>, Record<never, never>>,
    'suppliers-components-supplier-filter-form': RouteRecordInfo<'suppliers-components-supplier-filter-form', '/suppliers/components/SupplierFilterForm', Record<never, never>, Record<never, never>>,
    'suppliers-components-supplier-message-dialog': RouteRecordInfo<'suppliers-components-supplier-message-dialog', '/suppliers/components/SupplierMessageDialog', Record<never, never>, Record<never, never>>,
    'suppliers-components-supplier-table': RouteRecordInfo<'suppliers-components-supplier-table', '/suppliers/components/SupplierTable', Record<never, never>, Record<never, never>>,
    'suppliers-index-supplier-backup': RouteRecordInfo<'suppliers-index-supplier-backup', '/suppliers/index/supplier/backup', Record<never, never>, Record<never, never>>,
  }
}
